In [ ]:
# Datatypes:--
#     The type of data which can be stored in variable/identifier


# A variable is like a container that stores the values



# Variable Naming Conventions :-
# 1) A variable cannot begin with number

# 2) The Variables are case sensitive.

# 3) Variable names should not be reserved word or keywords

# 4) No special Characters are used except underscore(_)

# 5) Variables should be have some specific meaning

# 6) variables can be of unlimited length


a = 50
A = 50

age = 45
Name =
places =




#Comments :--

#Single line Comments



"""
Multi Line Comments

"""

In [ ]:
Types of Datatypes:--

1) Numbers

2) String

3) List

4) tuple

5) Dictionary

6) Boolean

7) Set

In [ ]:
# Assignment Questions:--

In [ ]:
#Question-1
# Create five Numbers  Variables and Assign Some Values in it and display the Output of  that Variables

#integer
a=10
age=23
#float
c=1.3454
salary=1456.9
#complex
x=3+5j
z=7-2j

print(a)
print(age)
print(c)
print(salary)
print(x)
print(z)

10
23
1.3454
1456.9
(3+5j)
(7-2j)

In [ ]:
#Question-2
# Create Five String Variables and Assigns Some Values in it and display the Output of that Variables
n1="shubhangi"
print(n1)

n2='s'
print(n2)

lang="python"
print(type(lang))

shubhangi
s
<class 'str'>

In [ ]:
#Question-3
# Store Days of the week  in One Variable
weekdays=("Monday","Tuesday","Wednesday","Thursday","Friday","Satursday","sunday")
print(weekdays)

('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Satursday', 'sunday')

In [ ]:
#Question-4
# Store at least 10  Floating point Number in one Variable
x=(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,0.10)
print(x)

(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.1)

In [ ]:
#Question-5
# Create a Dictionary to store the data of Square of the Given Nos upto 10
d=dict()
for x in range(1,10):
  d[x]=x**2

print(d)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}

In [ ]:
#Question-6
# Create Five SET Variables and Assigns Some Values in it and display the Output of that Variables
number={10,20,30,40,50}
print(number)
string={'a','e','i','o','u'}
print(string)
mixed={'hello',12,-2,'a'}
print(mixed)

{50, 20, 40, 10, 30}
{'u', 'o', 'e', 'i', 'a'}
{'hello', 12, -2, 'a'}

In [ ]:
#Question-7
# Create Five Tuples Variables and Assigns Some Values in it and display the Output of that Variables
t1=(1,2,3,4,5)
t2=("hello","Python")
t3=(1.2,3.4,5.6,7.8)
print(t1,t2,t3)

(1, 2, 3, 4, 5) ('hello', 'Python') (1.2, 3.4, 5.6, 7.8)

In [ ]:
#Question-8
# a = 72e3
# What is the meaning of a ?
int

In [ ]:
#Question-9
# b = 72e-5
# What is the meaning of a ?
 float

In [ ]:
#Question-10

# Create Five different data types of variables and Show the type of the variable:-
 #Boolean
a=10
b=5
print(a<b)

#string
n1="shubhangi"
print(n1)

#set
s1 = {1,2,3,4,5,6,7}
print(s1)

#tuple
t2 = ("Students" , 1,2,4,56,6,3.12432,546 , 'h' , "jkjsd")
print(t2)

#list
l1=["shubhangi"]
l2=["jagan"]
l3=["dhobale"]
print(l1,l2,l3)

False
shubhangi
{1, 2, 3, 4, 5, 6, 7}
('Students', 1, 2, 4, 56, 6, 3.12432, 546, 'h', 'jkjsd')
['shubhangi'] ['jagan'] ['dhobale']